const IMAGE = {
  ICON_ID: require('../../icon/ID.png'),
  ICON_PASSWORD: require('../../icon/password.png'),
  ICON_ACOUNT: require('../../icon/account.png'),
  ICON_MENU: require('../../icon/menu.png'),
  ICON_BACK: require('../../icon/back.png'),
  ICON_HOME: require('../../icon/home.png'),
  ICON_HOMEBLACK: require('../../icon/homeBlack.png'),
  ICON_MORE: require('../../icon/moreWhite.png'),
  ICON_MORE_BLACK: require('../../icon/moreBlack.png'),
  ICON_FOOTER_CARD: require('../../icon/footerCard.png'),
  ICON_CART: require('../../icon/cartWhite.png'),
  ICON_CART_BLACK: require('../../icon/cartBlack.png'),
  ICON_LOGO_START: require('../../icon/logoTravel.png'),
  ICON_HISTORY: require('../../icon/history.png'),
  ICON_HISTORY_BLACK: require('../../icon/historyBlack.png'),
  ICON_DELETE: require('../../icon/delete.png'),
  IMG_HALONG: require('../../image/vinhHaLong.jpg'),
  IMG_HANOI: require('../../image/haNoi.jpg'),
  IMG_RUONGBT: require('../../image/ruongBacThang.jpg'),
  IMG_BANNER1: 'http://192.168.1.8:81/img/banner.jpg',
  IMG_BANNER2: 'http://192.168.1.8:81/img/banner1.jpg',
  IMG_BANNER3: 'http://192.168.1.8:81/img/banner3.jpg',
  IMG_BANNER4: 'http://192.168.1.8:81/img/banner4.jpg',
  IMG_SEARCH: require('../../icon/search.png'),
  IMG_SEARCHBLACK: require('../../icon/searchBlack.png'),
  IMG_BACKGROUND_SINGIN: require('../../image/backGroundSingIn.jpg'),
};

export {IMAGE};
